/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MicrophoneCapture {
  /**
   * `device_id`    — CPAL device name or `None` for system default.
   * `vad_disabled` — set `true` when no external audio device is present
   *                  (built-in mic scenario) to bypass local silence gating.
   * `options`      — optional CaptureOptions (echo pipeline mode etc.).
   */
  constructor(deviceId?: string | undefined | null, vadDisabled?: boolean | undefined | null, options?: CaptureOptions | undefined | null)
  getSampleRate(): number
  getOutputSampleRate(): number
  start(callback: ((err: Error | null, arg: Buffer) => any), onSpeechEnded?: (((err: Error | null, arg: boolean) => any)) | undefined | null): void
  stop(): void
}

export declare class SystemAudioCapture {
  constructor(deviceId?: string | undefined | null, options?: CaptureOptions | undefined | null)
  getSampleRate(): number
  getOutputSampleRate(): number
  start(callback: ((err: Error | null, arg: Buffer) => any), onSpeechEnded?: (((err: Error | null, arg: boolean) => any)) | undefined | null): void
  stop(): void
}

export interface AudioDeviceInfo {
  id: string
  name: string
}

/**
 * Optional trailing options object accepted by both capture constructors.
 * Backward compatible: older JS that omits it (or passes extra unknown keys)
 * keeps working against a newer .node, and vice versa.
 */
export interface CaptureOptions {
  /**
   * Echo pipeline mode: "legacy" | "phase1" | "full_duplex".
   * Overrides the NATIVELY_ECHO_MODE env var. Unknown values are ignored.
   */
  echoMode?: string
  /** Bypass the local RMS+VAD gate (see MicrophoneCapture docs). */
  vadDisabled?: boolean
  /**
   * Persisted echo-alignment seed from a previous session on this machine
   * (ms, signed EFFECTIVE offset: positive = render delayed, negative =
   * capture delayed) — pass back the applied_align_offset_ms value from
   * getAudioPipelineStats(). Omitted/undefined = no seed for the current
   * route (the session starts unseeded / on the backend default); 0 is a
   * REAL seed meaning "converged with no alignment applied". Consumed by
   * MicrophoneCapture only; applied on the next mic-session start
   * (full_duplex only — legacy/phase1 always run with zero delay targets).
   */
  echoAlignSeedMs?: number
}

/**
 * JSON snapshot of the echo pipeline (mode, gate state, ERLE, delay,
 * alignment, mute ratio). Poll from JS for field telemetry / debug panel.
 */
export declare function getAudioPipelineStats(): string

/**
 * Returns a deterministic hardware fingerprint (SHA-256 hash of the machine UID).
 * This is used to lock license keys to a specific physical device.
 */
export declare function getHardwareId(): string

export declare function getInputDevices(): Array<AudioDeviceInfo>

/**
 * Capability probe for the JS layer. Older binaries lack this export, so JS
 * treats the level as 0. Bump when the native audio contract changes in a way
 * JS needs to detect at runtime.
 *   0 (implicit, older binaries) — no continuity guarantee.
 *   2 — the capture layer keeps the sample ring continuously fed during silence:
 *       the macOS tap streams silence natively, and the Windows WASAPI loopback
 *       synthesizes silence during render-idle instead of stalling. Lets the JS
 *       capture-stall watchdog relax to a long last-resort window rather than
 *       aggressively restarting capture (which interrupts the STT stream).
 */
export declare function getNativeFeatureLevel(): number

export declare function getOutputDevices(): Array<AudioDeviceInfo>

/**
 * Classify the current default output device: headphones have no acoustic
 * path to the mic, so the echo gate is bypassed while they are active.
 */
export declare function getOutputRoute(): OutputRouteJs

export interface OutputRouteJs {
  /** "headphones" | "speakers" | "unknown" */
  kind: string
  transport: string
  name: string
}

/**
 * Validates a Gumroad license key by calling the Gumroad Licenses API.
 * Returns a Promise that resolves to "OK" on success, or an error message string on failure.
 * The HTTP call runs on a libuv worker thread to prevent blocking the Node.js event loop.
 */
export declare function verifyGumroadKey(licenseKey: string): Promise<unknown>
